INSERT INTO products (stock, name, description, category) VALUES
(100, 'The Great Gatsby', 'A novel by F. Scott Fitzgerald', 'BOOKS'),
(50, 'Running Shoes', 'Comfortable running shoes for all terrains', 'FASHION'),
(30, 'Gaming Laptop', 'High-performance laptop for gaming and work', 'COMPUTERS'),
(20, 'Smartphone', 'Latest model smartphone with advanced features', 'ELECTRONICS'),
(15, 'Chess Set', 'A complete chess set for enthusiasts', 'GAMES'),
(200, 'Wireless Headphones', 'Noise-cancelling wireless headphones', 'ELECTRONICS'),
(75, 'Python Programming Book', 'Learn Python with practical examples', 'BOOKS'),
(10, 'Fashion Backpack', 'Stylish and spacious backpack for daily use', 'FASHION'),
(5, '4K Monitor', 'Ultra HD monitor for graphic design and gaming', 'COMPUTERS'),
(25, 'Action Video Game', 'Exciting action game for console', 'GAMES'),
(120, 'Wireless Mouse', 'Ergonomic wireless mouse with long battery life', 'COMPUTERS'),
(60, 'Leather Jacket', 'Stylish leather jacket for both men and women', 'FASHION'),
(40, 'Gardening Tools Set', 'Complete set for gardening enthusiasts', 'ELECTRONICS'),
(150, 'Fantasy Novel', 'An epic fantasy novel full of adventure', 'BOOKS'),
(30, 'Board Game', 'Fun board game for family nights', 'GAMES'),
(90, 'Bluetooth Speaker', 'Portable speaker with high-quality sound', 'ELECTRONICS'),
(80, 'Laptop Stand', 'Adjustable stand for better ergonomics while working', 'COMPUTERS'),
(55, 'Casual T-Shirt', 'Comfortable cotton t-shirt in various colors', 'FASHION'),
(10, 'Video Game Console', 'Latest generation gaming console', 'GAMES'),
(200, 'Cooking Essentials', 'Set of essential cooking tools and utensils', 'ELECTRONICS');